// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDZuguLCdIdL-t-kw7ryQPY_cR1oIPQk',
    appId: '1:171326931478:web:ca607b0b7239a752b06b37',
    messagingSenderId: '171326931478',
    projectId: 'tavanairegistrationapp',
    authDomain: 'tavanairegistrationapp.firebaseapp.com',
    storageBucket: 'tavanairegistrationapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnCmp8Ze7K0icLYErhxK19L9OgpQZ9NUg',
    appId: '1:171326931478:android:487aa4060ed8d2d7b06b37',
    messagingSenderId: '171326931478',
    projectId: 'tavanairegistrationapp',
    storageBucket: 'tavanairegistrationapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9xLiAZJM9hBOizF5MiAZpVMovjGeUegs',
    appId: '1:171326931478:ios:1e2508b98c9091e7b06b37',
    messagingSenderId: '171326931478',
    projectId: 'tavanairegistrationapp',
    storageBucket: 'tavanairegistrationapp.appspot.com',
    iosBundleId: 'com.example.tavanaiadminregistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9xLiAZJM9hBOizF5MiAZpVMovjGeUegs',
    appId: '1:171326931478:ios:1e2508b98c9091e7b06b37',
    messagingSenderId: '171326931478',
    projectId: 'tavanairegistrationapp',
    storageBucket: 'tavanairegistrationapp.appspot.com',
    iosBundleId: 'com.example.tavanaiadminregistration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVDZuguLCdIdL-t-kw7ryQPY_cR1oIPQk',
    appId: '1:171326931478:web:9af3c7e4012d1f96b06b37',
    messagingSenderId: '171326931478',
    projectId: 'tavanairegistrationapp',
    authDomain: 'tavanairegistrationapp.firebaseapp.com',
    storageBucket: 'tavanairegistrationapp.appspot.com',
  );
}
